apiRules:
  - include:
      uidRegex: ^Ibralogue
      type: Namespace
  - include:
      uidRegex: Ibralogue.Core
      type: Namespace
  - include:
      uidRegex: ^Global
      type: Namespace
  - exclude:
      uidRegex: .*
      type: Namespace
