name: Version Updater

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ibsemup
      uses: ibra/ibsemup@v1

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: Bump Package Version
          commit_options: "--no-verify --signoff"
          file_pattern: package.json
